# Generated by Django 3.0.7 on 2020-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.IntegerField(blank=True, default='def_img.jpg', null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('client', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
