# Generated by Django 3.0.7 on 2020-08-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rakesh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
