# Generated by Django 3.0.7 on 2020-08-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakesh', '0002_auto_20200810_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='def_img.jpg', null=True, upload_to=''),
        ),
    ]
