# Generated by Django 3.0.7 on 2020-08-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakesh', '0003_auto_20200810_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_filter',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
