# Generated by Django 3.0.7 on 2020-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakesh', '0005_auto_20200810_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='def_img.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_filter',
            field=models.CharField(blank=True, choices=[('filter-app', 'RA'), ('filter-card', 'Autotest'), ('filter-web', 'Freelance')], max_length=50, null=True),
        ),
    ]
