# Generated by Django 3.0.7 on 2020-08-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakesh', '0007_auto_20200811_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='def_img1.jpg', null=True, upload_to=''),
        ),
    ]
