# Generated by Django 3.0.7 on 2020-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakesh', '0010_auto_20200811_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyResumeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_headline', models.TextField(blank=True, null=True)),
                ('current_profile', models.CharField(max_length=100, null=True)),
                ('current_profile_details', models.TextField(blank=True, null=True)),
                ('my_age', models.CharField(max_length=100, null=True)),
                ('my_phone', models.CharField(max_length=100, null=True)),
                ('my_current_location', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('freelance', models.CharField(max_length=100, null=True)),
                ('about_myself', models.TextField(blank=True, null=True)),
                ('skills_details', models.TextField(blank=True, null=True)),
                ('skill1', models.CharField(max_length=100, null=True)),
                ('skill1_percentage', models.CharField(max_length=100, null=True)),
                ('skill2', models.CharField(max_length=100, null=True)),
                ('skill2_percentage', models.CharField(max_length=100, null=True)),
                ('skill3', models.CharField(max_length=100, null=True)),
                ('skill3_percentage', models.CharField(max_length=100, null=True)),
                ('skill4', models.CharField(max_length=100, null=True)),
                ('skill4_percentage', models.CharField(max_length=100, null=True)),
                ('skill5', models.CharField(max_length=100, null=True)),
                ('skill5_percentage', models.CharField(max_length=100, null=True)),
                ('skill6', models.CharField(max_length=100, null=True)),
                ('skill6_percentage', models.CharField(max_length=100, null=True)),
                ('resume_summary', models.TextField(blank=True, null=True)),
                ('education1_name', models.CharField(max_length=100, null=True)),
                ('education1_year', models.CharField(max_length=100, null=True)),
                ('education1_univ_name', models.TextField(blank=True, null=True)),
                ('education1_board', models.CharField(max_length=100, null=True)),
                ('education2_name', models.CharField(max_length=100, null=True)),
                ('education2_year', models.CharField(max_length=100, null=True)),
                ('education2_univ_name', models.TextField(blank=True, null=True)),
                ('education2_board', models.CharField(max_length=100, null=True)),
                ('exp1_profile', models.CharField(max_length=100, null=True)),
                ('exp1_duration', models.CharField(max_length=100, null=True)),
                ('exp1_company', models.CharField(max_length=100, null=True)),
                ('exp1_role1', models.TextField(blank=True, null=True)),
                ('exp1_role2', models.TextField(blank=True, null=True)),
                ('exp1_role3', models.TextField(blank=True, null=True)),
                ('exp2_profile', models.CharField(max_length=100, null=True)),
                ('exp2_duration', models.CharField(max_length=100, null=True)),
                ('exp2_company', models.CharField(max_length=100, null=True)),
                ('exp2_role1', models.TextField(blank=True, null=True)),
                ('exp2_role2', models.TextField(blank=True, null=True)),
                ('exp2_role3', models.TextField(blank=True, null=True)),
                ('exp3_profile', models.CharField(max_length=100, null=True)),
                ('exp3_duration', models.CharField(max_length=100, null=True)),
                ('exp3_company', models.CharField(max_length=100, null=True)),
                ('exp3_role1', models.TextField(blank=True, null=True)),
                ('exp3_role2', models.TextField(blank=True, null=True)),
                ('exp3_role3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
